module.exports = {
    // TOKEN OF DISCORD APPLICATION
    TOKEN: '',
    // SERVER ID
    SERVER_ID: '',
    // CHANNEL FOR INFO MESSAGES
    TEXT_CH: '',
    // CHANNEL FOR RADIO STREAM
    VOICE_CH: '',
    // URL TO RADIO STREAM (Icecast/SHOUTcast)
    STREAM: '',
    // YOUTUBE DATA API KEY
    YOUTUBE_KEY: '',
    // USERAGENT TO USE FOR CONNECTION
    USER_AGENT: '',
    // MINIMUM RANK NAME FOR PLAYRADIO COMMAND
    PLAYRADIO_MINRANK: '',
    // SEND MORE DEBUG MESSAGES
    DEBUG: false
};