module.exports = {
    // TOKEN OF DISCORD APPLICATION
    TOKEN: '',
    // SERVER ID
    SERVER_ID: '',
    // CHANNEL FOR INFO MESSAGES
    TEXT_CHANNEL: '',
    // CHANNEL FOR RADIO STREAM
    VOICE_CHANNEL: '',
    // URL TO RADIO STREAM (Icecast/SHOUTcast)
    STREAM: '',
    // SEND MORE DEBUG MESSAGES
    DEBUG: false
};